/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CcpOrdersGet200Response {
    #[serde(rename = "orders", skip_serializing_if = "Option::is_none")]
    pub orders: Option<Vec<models::OrderData>>,
}

impl CcpOrdersGet200Response {
    pub fn new() -> CcpOrdersGet200Response {
        CcpOrdersGet200Response {
            orders: None,
        }
    }
}

