/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CcpAccountGet200Response {
    /// The primary or parent account.
    #[serde(rename = "mainAcct", skip_serializing_if = "Option::is_none")]
    pub main_acct: Option<String>,
    /// List of tradeable or Sub Accounts
    #[serde(rename = "acctList", skip_serializing_if = "Option::is_none")]
    pub acct_list: Option<Vec<models::CcpAccountGet200ResponseAcctListInner>>,
}

impl CcpAccountGet200Response {
    pub fn new() -> CcpAccountGet200Response {
        CcpAccountGet200Response {
            main_acct: None,
            acct_list: None,
        }
    }
}

