/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CcpAuthResponsePost200Response {
    /// If sso authentication completed
    #[serde(rename = "passed", skip_serializing_if = "Option::is_none")]
    pub passed: Option<bool>,
    /// If connection is authenticated
    #[serde(rename = "authenticated", skip_serializing_if = "Option::is_none")]
    pub authenticated: Option<bool>,
    /// Connected to CCP session
    #[serde(rename = "connected", skip_serializing_if = "Option::is_none")]
    pub connected: Option<bool>,
    /// If user already has an existing brokerage session running.
    #[serde(rename = "competing", skip_serializing_if = "Option::is_none")]
    pub competing: Option<bool>,
}

impl CcpAuthResponsePost200Response {
    pub fn new() -> CcpAuthResponsePost200Response {
        CcpAuthResponsePost200Response {
            passed: None,
            authenticated: None,
            connected: None,
            competing: None,
        }
    }
}

