/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CcpAuthInitPost200Response {
    /// Challenge in hex format
    #[serde(rename = "challenge", skip_serializing_if = "Option::is_none")]
    pub challenge: Option<serde_json::Value>,
}

impl CcpAuthInitPost200Response {
    pub fn new() -> CcpAuthInitPost200Response {
        CcpAuthInitPost200Response {
            challenge: None,
        }
    }
}

