/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FyiUnreadnumberGet200Response {
    /// unread number
    #[serde(rename = "BN", skip_serializing_if = "Option::is_none")]
    pub bn: Option<i32>,
}

impl FyiUnreadnumberGet200Response {
    pub fn new() -> FyiUnreadnumberGet200Response {
        FyiUnreadnumberGet200Response {
            bn: None,
        }
    }
}

