/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FyiDeliveryoptionsDevicePostRequest {
    #[serde(rename = "devicename", skip_serializing_if = "Option::is_none")]
    pub devicename: Option<String>,
    #[serde(rename = "deviceId", skip_serializing_if = "Option::is_none")]
    pub device_id: Option<String>,
    #[serde(rename = "uiName", skip_serializing_if = "Option::is_none")]
    pub ui_name: Option<String>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
}

impl FyiDeliveryoptionsDevicePostRequest {
    pub fn new() -> FyiDeliveryoptionsDevicePostRequest {
        FyiDeliveryoptionsDevicePostRequest {
            devicename: None,
            device_id: None,
            ui_name: None,
            enabled: None,
        }
    }
}

