/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FyiSettingsTypecodePostRequest {
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
}

impl FyiSettingsTypecodePostRequest {
    pub fn new() -> FyiSettingsTypecodePostRequest {
        FyiSettingsTypecodePostRequest {
            enabled: None,
        }
    }
}

