/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FyiDeliveryoptionsGet200Response {
    /// Email option is enabled or not 0-off, 1-on.
    #[serde(rename = "M", skip_serializing_if = "Option::is_none")]
    pub m: Option<i32>,
    #[serde(rename = "E", skip_serializing_if = "Option::is_none")]
    pub e: Option<Vec<models::FyiDeliveryoptionsGet200ResponseEInner>>,
}

impl FyiDeliveryoptionsGet200Response {
    pub fn new() -> FyiDeliveryoptionsGet200Response {
        FyiDeliveryoptionsGet200Response {
            m: None,
            e: None,
        }
    }
}

