/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FyiDisclaimerTypecodeGet200Response {
    /// disclaimer message
    #[serde(rename = "DT", skip_serializing_if = "Option::is_none")]
    pub dt: Option<String>,
    /// fyi code
    #[serde(rename = "FC", skip_serializing_if = "Option::is_none")]
    pub fc: Option<String>,
}

impl FyiDisclaimerTypecodeGet200Response {
    pub fn new() -> FyiDisclaimerTypecodeGet200Response {
        FyiDisclaimerTypecodeGet200Response {
            dt: None,
            fc: None,
        }
    }
}

