/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HmdsScannerPostRequestFiltersInner {
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// Value can be either an integer, double, boolean or a string depending upon the type of filter specified in the code section
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<serde_json::Value>,
}

impl HmdsScannerPostRequestFiltersInner {
    pub fn new() -> HmdsScannerPostRequestFiltersInner {
        HmdsScannerPostRequestFiltersInner {
            code: None,
            value: None,
        }
    }
}

