/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IserverAccountAccountIdOrderWhatifPost200ResponseEquity {
    #[serde(rename = "current", skip_serializing_if = "Option::is_none")]
    pub current: Option<String>,
    #[serde(rename = "change", skip_serializing_if = "Option::is_none")]
    pub change: Option<String>,
    #[serde(rename = "after", skip_serializing_if = "Option::is_none")]
    pub after: Option<String>,
}

impl IserverAccountAccountIdOrderWhatifPost200ResponseEquity {
    pub fn new() -> IserverAccountAccountIdOrderWhatifPost200ResponseEquity {
        IserverAccountAccountIdOrderWhatifPost200ResponseEquity {
            current: None,
            change: None,
            after: None,
        }
    }
}

