/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IserverContractRulesPost200ResponseRulesInnerTifTypesInner {
    /// Time in Force values, formatted with o for supporting Outside regular trading hours and a for Algo trading
    #[serde(rename = "0", skip_serializing_if = "Option::is_none")]
    pub param_0: Option<String>,
}

impl IserverContractRulesPost200ResponseRulesInnerTifTypesInner {
    pub fn new() -> IserverContractRulesPost200ResponseRulesInnerTifTypesInner {
        IserverContractRulesPost200ResponseRulesInnerTifTypesInner {
            param_0: None,
        }
    }
}

