/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IserverAccountPost200Response {
    #[serde(rename = "set", skip_serializing_if = "Option::is_none")]
    pub set: Option<bool>,
    #[serde(rename = "acctId", skip_serializing_if = "Option::is_none")]
    pub acct_id: Option<String>,
}

impl IserverAccountPost200Response {
    pub fn new() -> IserverAccountPost200Response {
        IserverAccountPost200Response {
            set: None,
            acct_id: None,
        }
    }
}

