/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IserverSecdefSearchPost200ResponseInner {
    /// Contract Identifier
    #[serde(rename = "conid", skip_serializing_if = "Option::is_none")]
    pub conid: Option<i32>,
    /// Company Name - Exchange
    #[serde(rename = "companyHeader", skip_serializing_if = "Option::is_none")]
    pub company_header: Option<String>,
    #[serde(rename = "companyName", skip_serializing_if = "Option::is_none")]
    pub company_name: Option<String>,
    /// Underlying symbol
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// Exchange
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "restricted", skip_serializing_if = "Option::is_none")]
    pub restricted: Option<String>,
    /// List of Future Option expirations in YYYMMDD format separated by semicolon
    #[serde(rename = "fop", skip_serializing_if = "Option::is_none")]
    pub fop: Option<String>,
    /// List of Option expirations in YYYYMMDD format separated by semicolon
    #[serde(rename = "opt", skip_serializing_if = "Option::is_none")]
    pub opt: Option<String>,
    /// List of Warrant expirations in YYYYMMDD format separated by semicolon
    #[serde(rename = "war", skip_serializing_if = "Option::is_none")]
    pub war: Option<String>,
    #[serde(rename = "sections", skip_serializing_if = "Option::is_none")]
    pub sections: Option<Vec<models::IserverSecdefSearchPost200ResponseInnerSectionsInner>>,
}

impl IserverSecdefSearchPost200ResponseInner {
    pub fn new() -> IserverSecdefSearchPost200ResponseInner {
        IserverSecdefSearchPost200ResponseInner {
            conid: None,
            company_header: None,
            company_name: None,
            symbol: None,
            description: None,
            restricted: None,
            fop: None,
            opt: None,
            war: None,
            sections: None,
        }
    }
}

