/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IserverSecdefStrikesGet200Response {
    #[serde(rename = "call", skip_serializing_if = "Option::is_none")]
    pub call: Option<Vec<String>>,
    #[serde(rename = "put", skip_serializing_if = "Option::is_none")]
    pub put: Option<Vec<String>>,
}

impl IserverSecdefStrikesGet200Response {
    pub fn new() -> IserverSecdefStrikesGet200Response {
        IserverSecdefStrikesGet200Response {
            call: None,
            put: None,
        }
    }
}

