/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IserverAccountAccountIdOrderOrderIdPost200ResponseInner {
    #[serde(rename = "order_id", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<String>,
    #[serde(rename = "local_order_id", skip_serializing_if = "Option::is_none")]
    pub local_order_id: Option<String>,
    #[serde(rename = "order_status", skip_serializing_if = "Option::is_none")]
    pub order_status: Option<String>,
}

impl IserverAccountAccountIdOrderOrderIdPost200ResponseInner {
    pub fn new() -> IserverAccountAccountIdOrderOrderIdPost200ResponseInner {
        IserverAccountAccountIdOrderOrderIdPost200ResponseInner {
            order_id: None,
            local_order_id: None,
            order_status: None,
        }
    }
}

