/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IserverAccountPnlPartitionedGet200Response {
    #[serde(rename = "acctId", skip_serializing_if = "Option::is_none")]
    pub acct_id: Option<serde_json::Value>,
}

impl IserverAccountPnlPartitionedGet200Response {
    pub fn new() -> IserverAccountPnlPartitionedGet200Response {
        IserverAccountPnlPartitionedGet200Response {
            acct_id: None,
        }
    }
}

