/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IserverContractRulesPost200ResponseRulesInnerOrderTypesOutsideInner {
    /// order types that support outside of regular trading hours
    #[serde(rename = "0", skip_serializing_if = "Option::is_none")]
    pub param_0: Option<String>,
}

impl IserverContractRulesPost200ResponseRulesInnerOrderTypesOutsideInner {
    pub fn new() -> IserverContractRulesPost200ResponseRulesInnerOrderTypesOutsideInner {
        IserverContractRulesPost200ResponseRulesInnerOrderTypesOutsideInner {
            param_0: None,
        }
    }
}

