/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IserverContractRulesPostRequest {
    /// IBKR contract identifier
    #[serde(rename = "conid")]
    pub conid: String,
    /// Side of the market rules apply too. Set to **true** for Buy Orders, set to **false** for Sell Orders
    #[serde(rename = "isBuy")]
    pub is_buy: bool,
}

impl IserverContractRulesPostRequest {
    pub fn new(conid: String, is_buy: bool) -> IserverContractRulesPostRequest {
        IserverContractRulesPostRequest {
            conid,
            is_buy,
        }
    }
}

