/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IserverAccountAccountIdOrderWhatifPost200ResponseAmount {
    /// for example 23,000 USD
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<String>,
    /// for example 1.1 ... 1.2 USD
    #[serde(rename = "commission", skip_serializing_if = "Option::is_none")]
    pub commission: Option<String>,
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<String>,
}

impl IserverAccountAccountIdOrderWhatifPost200ResponseAmount {
    pub fn new() -> IserverAccountAccountIdOrderWhatifPost200ResponseAmount {
        IserverAccountAccountIdOrderWhatifPost200ResponseAmount {
            amount: None,
            commission: None,
            total: None,
        }
    }
}

