/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IserverMarketdataConidUnsubscribeGet200Response {
    /// success means market data was cancelled.
    #[serde(rename = "confirmed", skip_serializing_if = "Option::is_none")]
    pub confirmed: Option<String>,
}

impl IserverMarketdataConidUnsubscribeGet200Response {
    pub fn new() -> IserverMarketdataConidUnsubscribeGet200Response {
        IserverMarketdataConidUnsubscribeGet200Response {
            confirmed: None,
        }
    }
}

