/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IserverAccountAccountIdOrderWhatifPost200Response {
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<Box<models::IserverAccountAccountIdOrderWhatifPost200ResponseAmount>>,
    #[serde(rename = "equity", skip_serializing_if = "Option::is_none")]
    pub equity: Option<Box<models::IserverAccountAccountIdOrderWhatifPost200ResponseEquity>>,
    #[serde(rename = "initial", skip_serializing_if = "Option::is_none")]
    pub initial: Option<Box<models::IserverAccountAccountIdOrderWhatifPost200ResponseEquity>>,
    #[serde(rename = "maintenance", skip_serializing_if = "Option::is_none")]
    pub maintenance: Option<Box<models::IserverAccountAccountIdOrderWhatifPost200ResponseEquity>>,
    #[serde(rename = "warn", skip_serializing_if = "Option::is_none")]
    pub warn: Option<String>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

impl IserverAccountAccountIdOrderWhatifPost200Response {
    pub fn new() -> IserverAccountAccountIdOrderWhatifPost200Response {
        IserverAccountAccountIdOrderWhatifPost200Response {
            amount: None,
            equity: None,
            initial: None,
            maintenance: None,
            warn: None,
            error: None,
        }
    }
}

