/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IserverReplyReplyidPostRequest {
    /// answer to question, true means yes, false means no
    #[serde(rename = "confirmed", skip_serializing_if = "Option::is_none")]
    pub confirmed: Option<bool>,
}

impl IserverReplyReplyidPostRequest {
    pub fn new() -> IserverReplyReplyidPostRequest {
        IserverReplyReplyidPostRequest {
            confirmed: None,
        }
    }
}

