/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IserverContractRulesPost200ResponseRulesInnerOrderDefaultsInner {
    /// orderType
    #[serde(rename = "string", skip_serializing_if = "Option::is_none")]
    pub string: Option<Vec<models::IserverContractRulesPost200ResponseRulesInnerOrderDefaultsInnerStringInner>>,
}

impl IserverContractRulesPost200ResponseRulesInnerOrderDefaultsInner {
    pub fn new() -> IserverContractRulesPost200ResponseRulesInnerOrderDefaultsInner {
        IserverContractRulesPost200ResponseRulesInnerOrderDefaultsInner {
            string: None,
        }
    }
}

