/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IserverScannerRunPost200ResponseInner {
    #[serde(rename = "server_id", skip_serializing_if = "Option::is_none")]
    pub server_id: Option<String>,
    #[serde(rename = "column_name", skip_serializing_if = "Option::is_none")]
    pub column_name: Option<String>,
    /// Underlying symbol
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// conid and exchange. Format supports conid or conid@exchange
    #[serde(rename = "conidex", skip_serializing_if = "Option::is_none")]
    pub conidex: Option<String>,
    #[serde(rename = "con_id", skip_serializing_if = "Option::is_none")]
    pub con_id: Option<f64>,
    /// List of available chart periods
    #[serde(rename = "available_chart_periods", skip_serializing_if = "Option::is_none")]
    pub available_chart_periods: Option<String>,
    /// Contracts company name
    #[serde(rename = "company_name", skip_serializing_if = "Option::is_none")]
    pub company_name: Option<String>,
    /// Format contract name
    #[serde(rename = "contract_description_1", skip_serializing_if = "Option::is_none")]
    pub contract_description_1: Option<String>,
    #[serde(rename = "listing_exchange", skip_serializing_if = "Option::is_none")]
    pub listing_exchange: Option<String>,
    #[serde(rename = "sec_type", skip_serializing_if = "Option::is_none")]
    pub sec_type: Option<String>,
}

impl IserverScannerRunPost200ResponseInner {
    pub fn new() -> IserverScannerRunPost200ResponseInner {
        IserverScannerRunPost200ResponseInner {
            server_id: None,
            column_name: None,
            symbol: None,
            conidex: None,
            con_id: None,
            available_chart_periods: None,
            company_name: None,
            contract_description_1: None,
            listing_exchange: None,
            sec_type: None,
        }
    }
}

