/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IserverMarketdataUnsubscribeallGet200Response {
    /// true means market data is cancelled, false means it is not.
    #[serde(rename = "confirmed", skip_serializing_if = "Option::is_none")]
    pub confirmed: Option<bool>,
}

impl IserverMarketdataUnsubscribeallGet200Response {
    pub fn new() -> IserverMarketdataUnsubscribeallGet200Response {
        IserverMarketdataUnsubscribeallGet200Response {
            confirmed: None,
        }
    }
}

