/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaTransactionsPostRequest {
    #[serde(rename = "acctIds", skip_serializing_if = "Option::is_none")]
    pub acct_ids: Option<Vec<String>>,
    #[serde(rename = "conids", skip_serializing_if = "Option::is_none")]
    pub conids: Option<Vec<f64>>,
    /// optional defaults to USD.
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    /// optional, default value is 90
    #[serde(rename = "days", skip_serializing_if = "Option::is_none")]
    pub days: Option<f64>,
}

impl PaTransactionsPostRequest {
    pub fn new() -> PaTransactionsPostRequest {
        PaTransactionsPostRequest {
            acct_ids: None,
            conids: None,
            currency: None,
            days: None,
        }
    }
}

