/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PortfolioSubaccounts2Get200ResponseMetadata {
    /// Number of sub-accounts
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<f64>,
    /// How many sub-accounts are returned for the page requested. A max of 20 per page.
    #[serde(rename = "pageSize", skip_serializing_if = "Option::is_none")]
    pub page_size: Option<f64>,
    /// Current page number.
    #[serde(rename = "pageNume", skip_serializing_if = "Option::is_none")]
    pub page_nume: Option<f64>,
}

impl PortfolioSubaccounts2Get200ResponseMetadata {
    pub fn new() -> PortfolioSubaccounts2Get200ResponseMetadata {
        PortfolioSubaccounts2Get200ResponseMetadata {
            total: None,
            page_size: None,
            page_nume: None,
        }
    }
}

