/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PortfolioPositionsConidGet200Response {
    #[serde(rename = "ACCTID", skip_serializing_if = "Option::is_none")]
    pub acctid: Option<Vec<models::PositionInner>>,
}

impl PortfolioPositionsConidGet200Response {
    pub fn new() -> PortfolioPositionsConidGet200Response {
        PortfolioPositionsConidGet200Response {
            acctid: None,
        }
    }
}

