/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrsrvSecdefPostRequest {
    #[serde(rename = "conids", skip_serializing_if = "Option::is_none")]
    pub conids: Option<Vec<i32>>,
}

impl TrsrvSecdefPostRequest {
    pub fn new() -> TrsrvSecdefPostRequest {
        TrsrvSecdefPostRequest {
            conids: None,
        }
    }
}

