/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrsrvStocksGet200Response {
    /// This is an array of object(s), there could be multiple results under same symbol 
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<Vec<models::StocksInner>>,
}

impl TrsrvStocksGet200Response {
    pub fn new() -> TrsrvStocksGet200Response {
        TrsrvStocksGet200Response {
            symbol: None,
        }
    }
}

