/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrsrvFuturesGet200Response {
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<Vec<models::FuturesInner>>,
}

impl TrsrvFuturesGet200Response {
    pub fn new() -> TrsrvFuturesGet200Response {
        TrsrvFuturesGet200Response {
            symbol: None,
        }
    }
}

