/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AllocationInnerGroupShort : short positions allocation
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllocationInnerGroupShort {
    #[serde(rename = "Banks", skip_serializing_if = "Option::is_none")]
    pub banks: Option<f64>,
    #[serde(rename = "Airlines", skip_serializing_if = "Option::is_none")]
    pub airlines: Option<f64>,
    #[serde(rename = "Internet", skip_serializing_if = "Option::is_none")]
    pub internet: Option<f64>,
}

impl AllocationInnerGroupShort {
    /// short positions allocation
    pub fn new() -> AllocationInnerGroupShort {
        AllocationInnerGroupShort {
            banks: None,
            airlines: None,
            internet: None,
        }
    }
}

