/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AllocationInnerAssetClass : portfolio allocation by asset class
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllocationInnerAssetClass {
    #[serde(rename = "long", skip_serializing_if = "Option::is_none")]
    pub long: Option<Box<models::AllocationInnerAssetClassLong>>,
    #[serde(rename = "short", skip_serializing_if = "Option::is_none")]
    pub short: Option<Box<models::AllocationInnerAssetClassShort>>,
}

impl AllocationInnerAssetClass {
    /// portfolio allocation by asset class
    pub fn new() -> AllocationInnerAssetClass {
        AllocationInnerAssetClass {
            long: None,
            short: None,
        }
    }
}

