/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AllocationInnerSectorShort : short positions allocation
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllocationInnerSectorShort {
    #[serde(rename = "Industrial", skip_serializing_if = "Option::is_none")]
    pub industrial: Option<f64>,
    #[serde(rename = "Consumer", skip_serializing_if = "Option::is_none")]
    pub consumer: Option<f64>,
    #[serde(rename = "Diversified", skip_serializing_if = "Option::is_none")]
    pub diversified: Option<f64>,
}

impl AllocationInnerSectorShort {
    /// short positions allocation
    pub fn new() -> AllocationInnerSectorShort {
        AllocationInnerSectorShort {
            industrial: None,
            consumer: None,
            diversified: None,
        }
    }
}

