/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AllocationInner : allocation
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllocationInner {
    #[serde(rename = "assetClass", skip_serializing_if = "Option::is_none")]
    pub asset_class: Option<Box<models::AllocationInnerAssetClass>>,
    #[serde(rename = "sector", skip_serializing_if = "Option::is_none")]
    pub sector: Option<Box<models::AllocationInnerSector>>,
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<Box<models::AllocationInnerGroup>>,
}

impl AllocationInner {
    /// allocation
    pub fn new() -> AllocationInner {
        AllocationInner {
            asset_class: None,
            sector: None,
            group: None,
        }
    }
}

