/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AllocationInnerGroup : portfolio allocation by group
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllocationInnerGroup {
    #[serde(rename = "long", skip_serializing_if = "Option::is_none")]
    pub long: Option<Box<models::AllocationInnerGroupLong>>,
    #[serde(rename = "short", skip_serializing_if = "Option::is_none")]
    pub short: Option<Box<models::AllocationInnerGroupShort>>,
}

impl AllocationInnerGroup {
    /// portfolio allocation by group
    pub fn new() -> AllocationInnerGroup {
        AllocationInnerGroup {
            long: None,
            short: None,
        }
    }
}

