/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HistoryDataDataInner {
    /// open price
    #[serde(rename = "o", skip_serializing_if = "Option::is_none")]
    pub o: Option<f64>,
    /// close price
    #[serde(rename = "c", skip_serializing_if = "Option::is_none")]
    pub c: Option<f64>,
    /// high price
    #[serde(rename = "h", skip_serializing_if = "Option::is_none")]
    pub h: Option<f64>,
    /// low price
    #[serde(rename = "l", skip_serializing_if = "Option::is_none")]
    pub l: Option<f64>,
    /// volume
    #[serde(rename = "v", skip_serializing_if = "Option::is_none")]
    pub v: Option<f64>,
    /// unix time stamp
    #[serde(rename = "t", skip_serializing_if = "Option::is_none")]
    pub t: Option<f64>,
}

impl HistoryDataDataInner {
    pub fn new() -> HistoryDataDataInner {
        HistoryDataDataInner {
            o: None,
            c: None,
            h: None,
            l: None,
            v: None,
            t: None,
        }
    }
}

