/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndsInner {
    #[serde(rename = "conid", skip_serializing_if = "Option::is_none")]
    pub conid: Option<f64>,
}

impl IndsInner {
    pub fn new() -> IndsInner {
        IndsInner {
            conid: None,
        }
    }
}

