/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NotificationsInner : notification
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationsInner {
    /// notification date
    #[serde(rename = "D", skip_serializing_if = "Option::is_none")]
    pub d: Option<String>,
    /// unique way to reference this notification
    #[serde(rename = "ID", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// FYI code, we can use it to find whether the disclaimer is accepted or not in settings
    #[serde(rename = "FC", skip_serializing_if = "Option::is_none")]
    pub fc: Option<String>,
    /// content of notification
    #[serde(rename = "MD", skip_serializing_if = "Option::is_none")]
    pub md: Option<String>,
    /// title of notification
    #[serde(rename = "MS", skip_serializing_if = "Option::is_none")]
    pub ms: Option<String>,
    /// 0-unread, 1-read
    #[serde(rename = "R", skip_serializing_if = "Option::is_none")]
    pub r: Option<String>,
}

impl NotificationsInner {
    /// notification
    pub fn new() -> NotificationsInner {
        NotificationsInner {
            d: None,
            id: None,
            fc: None,
            md: None,
            ms: None,
            r: None,
        }
    }
}

