/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderDataWarnings {
    #[serde(rename = "PRICECAP", skip_serializing_if = "Option::is_none")]
    pub pricecap: Option<String>,
    #[serde(rename = "TIME", skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
}

impl OrderDataWarnings {
    pub fn new() -> OrderDataWarnings {
        OrderDataWarnings {
            pricecap: None,
            time: None,
        }
    }
}

