/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PerformanceCpsDataInner {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// for example-- acctid
    #[serde(rename = "idType", skip_serializing_if = "Option::is_none")]
    pub id_type: Option<String>,
    /// start date-- yyyyMMdd
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<String>,
    #[serde(rename = "baseCurrency", skip_serializing_if = "Option::is_none")]
    pub base_currency: Option<String>,
    /// each value stands for price change percent of corresponding date in dates array
    #[serde(rename = "returns", skip_serializing_if = "Option::is_none")]
    pub returns: Option<Vec<f64>>,
    /// end date-- yyyyMMdd
    #[serde(rename = "end", skip_serializing_if = "Option::is_none")]
    pub end: Option<String>,
}

impl PerformanceCpsDataInner {
    pub fn new() -> PerformanceCpsDataInner {
        PerformanceCpsDataInner {
            id: None,
            id_type: None,
            start: None,
            base_currency: None,
            returns: None,
            end: None,
        }
    }
}

