/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PositionData {
    /// Contract identifier from IBKR's database.
    #[serde(rename = "conid", skip_serializing_if = "Option::is_none")]
    pub conid: Option<f64>,
    /// Number of shares or quantity of the position.
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<f64>,
    /// Average cost of the position.
    #[serde(rename = "avgCost", skip_serializing_if = "Option::is_none")]
    pub avg_cost: Option<f64>,
}

impl PositionData {
    pub fn new() -> PositionData {
        PositionData {
            conid: None,
            position: None,
            avg_cost: None,
        }
    }
}

