/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SecdefInnerIncrementRules : Price increment value contract trades.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecdefInnerIncrementRules {
    /// The minimum contract price on the market that supports the specified increment.
    #[serde(rename = "lowerEdge", skip_serializing_if = "Option::is_none")]
    pub lower_edge: Option<f64>,
    /// The minimum increment value for contract price.
    #[serde(rename = "increment", skip_serializing_if = "Option::is_none")]
    pub increment: Option<f64>,
}

impl SecdefInnerIncrementRules {
    /// Price increment value contract trades.
    pub fn new() -> SecdefInnerIncrementRules {
        SecdefInnerIncrementRules {
            lower_edge: None,
            increment: None,
        }
    }
}

