/*
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionsTransactionsInner {
    #[serde(rename = "acctid", skip_serializing_if = "Option::is_none")]
    pub acctid: Option<String>,
    #[serde(rename = "conid", skip_serializing_if = "Option::is_none")]
    pub conid: Option<f64>,
    /// currency code
    #[serde(rename = "cur", skip_serializing_if = "Option::is_none")]
    pub cur: Option<String>,
    /// Conversion rate from asset currency to response currency
    #[serde(rename = "fxRate", skip_serializing_if = "Option::is_none")]
    pub fx_rate: Option<f64>,
    /// Transaction description
    #[serde(rename = "desc", skip_serializing_if = "Option::is_none")]
    pub desc: Option<String>,
    /// Date of transaction.  Epoch time, GMT
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    /// Transaction Type Name: Examples: \"Sell\", \"Buy\", \"Corporate Action\", \"Dividend Payment\", \"Transfer\", \"Payment in Lieu\" Dividends and Transfers do not have price and quantity in response 
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// Not applicable for all transaction types
    #[serde(rename = "qty", skip_serializing_if = "Option::is_none")]
    pub qty: Option<f64>,
    /// In asset currency. Not be applicable for all transaction types.
    #[serde(rename = "pr", skip_serializing_if = "Option::is_none")]
    pub pr: Option<f64>,
    /// Raw value, no formatting. Net transaction amount (may include commission, tax). In asset currency
    #[serde(rename = "amt", skip_serializing_if = "Option::is_none")]
    pub amt: Option<f64>,
}

impl TransactionsTransactionsInner {
    pub fn new() -> TransactionsTransactionsInner {
        TransactionsTransactionsInner {
            acctid: None,
            conid: None,
            cur: None,
            fx_rate: None,
            desc: None,
            date: None,
            r#type: None,
            qty: None,
            pr: None,
            amt: None,
        }
    }
}

